// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NETDLab5.Models;

namespace NETDLab5.Migrations
{
    [DbContext(typeof(VideoGameContext))]
    [Migration("20211211220202_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NETDLab5.Models.Store", b =>
                {
                    b.Property<int>("storeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("postalCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("storeID");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("NETDLab5.Models.VideoGame", b =>
                {
                    b.Property<int>("videoGameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("developer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isNew")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("platform")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("storeID")
                        .HasColumnType("int");

                    b.Property<int>("yearOfRelease")
                        .HasColumnType("int");

                    b.HasKey("videoGameID");

                    b.HasIndex("storeID");

                    b.ToTable("VideoGames");
                });

            modelBuilder.Entity("NETDLab5.Models.VideoGameConsole", b =>
                {
                    b.Property<int>("videoGameConsoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isNew")
                        .HasColumnType("bit");

                    b.Property<string>("manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("storeID")
                        .HasColumnType("int");

                    b.HasKey("videoGameConsoleID");

                    b.HasIndex("storeID");

                    b.ToTable("VideoGameConsole");
                });

            modelBuilder.Entity("NETDLab5.Models.VideoGame", b =>
                {
                    b.HasOne("NETDLab5.Models.Store", "store")
                        .WithMany("games")
                        .HasForeignKey("storeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NETDLab5.Models.VideoGameConsole", b =>
                {
                    b.HasOne("NETDLab5.Models.Store", "store")
                        .WithMany("gameConsoles")
                        .HasForeignKey("storeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
